### ISSUE TITLE
How to emit inside a regular handler

### ISSUE THREAD

**Issue by salarelv** [sibartlett/hapi-io#10]
I have a API call that does some stuff and if it successful I like to emit a event. The API call itself isn't a socket.io route.

**Comment by jalcine** [comment]
[**@salarelv**](https://github.com/salarelv) commented on [Aug 21, 2015, 1:16 PM EDT](https://github.com/sibartlett/hapi-io/issues/10#issue-102425014):

> I have a API call that does some stuff and if it successful I like to emit a event. The API call itself isn't a socket.io route.

Nabbing the socket.io handle shouldn't be too hard when you're in a route. That'd be [like this](https://github.com/sibartlett/hapi-io#raw-access-to-socketio). You could use that to do whatever you'd deem necessary.

**Comment by salarelv** [comment]
Something like that?
req.server.plugins["hapi-io"].io.emit("msg");

**Comment by jalcine** [comment]
[**@salarelv**](https://github.com/salarelv) commented on [Aug 25, 2015, 3:42 AM EDT](https://github.com/sibartlett/hapi-io/issues/10#issuecomment-134512241):

> Something like that?  
> 
> req.server.plugins["hapi-io"].io.emit("msg");

That looks like it'd work, yeah. I'd say to try it out :)

**Comment by sibartlett** [comment]
@salarelv that's correct, I hope it worked for you!

@jalcine thank you so much for helping out. I'm on vacation at the moment, so I really appreciate your help :)

**Comment by salarelv** [comment]
Yes, that worked. Maybe it is good to add it to the readme?

**Comment by jalcine** [comment]
[**@sibartlett**](https://github.com/sibartlett) commented on [Aug 27, 2015, 11:27 PM EDT](https://github.com/sibartlett/hapi-io/issues/10#issuecomment-135623353):

> [@jalcine](https://github.com/jalcine) thank you so much for helping out. I'm on vacation at the moment, so I really appreciate your help :)

No problem!

**Comment by jalcine** [comment]
[**@salarelv**](https://github.com/salarelv) commented on [Aug 28, 2015, 4:14 AM EDT](https://github.com/sibartlett/hapi-io/issues/10#issuecomment-135668420):

> Yes, that worked. Maybe it is good to add it to the readme?

It is :) https://github.com/sibartlett/hapi-io#raw-access-to-socketio
