### ISSUE TITLE
Decorate each request with the user's socket?

### ISSUE THREAD

**Issue by chriswiggins** [sibartlett/hapi-io#21]
Currently I'm using postHooks with this module to join sockets to rooms etc. Sometimes, the authorisation library will return a 403 for specific routes, but the postHook handler is still called.

I'm getting around this at the moment by `if(res.statusCode !== 200)` around my logic, but I was wondering whether it would be beneficial to have the `socket` variable available in the actual hapi request handler? Because when the auth library 403's, the request lifecycle immediately returns a 403 to the client and doesn't call any other logic. By making `socket` available in the request handler, I don't have to worry about sorting things out in a postHook handler.

Thoughts? Happy to submit a PR to make this happen (if its possible?)

**Comment by Gattermeier** [comment]
I second that. I am using the postHook to emit a specific event to the socket, which would be cleaner to do off the request object in the handler.

**Comment by sibartlett** [comment]
See the README: https://github.com/sibartlett/hapi-io#access-socket-during-hapi-request
