### ISSUE TITLE
socket.disconnect() in auth.js

### ISSUE THREAD

**Issue by ahthamrin** [sibartlett/hapi-io#24]
Would you explain what's the reason of not including socket.disconnect() in auth.js?
Using Chrome  49.0.2623.110 (64-bit) I found that without socket.disconnect(), the browser keeps alive the websocket's TCP connection to the server. 
I think it's should disconnect as below.

```
function(result) {
    if (!result) {
      next(new Error('Authentication Failed'));
      socket.disconnect();
    }
  });
```

**Comment by sibartlett** [comment]
The latest version now calls socket.disconnect()
