### ISSUE TITLE
Can't get socket-io instance from request directly

### ISSUE THREAD

**Issue by luizfilipe** [sibartlett/hapi-io#28]
I'm using plugins like `inert`, `hapi-router`, `hapi-sequelize` and `hapi-auth-jwt2`, I don't know if any of those plugins are breaking the expected behavior, but I can't get the `socket-io` instance from request directly, this means that `request.plugins['hapi-io'];` is undefined, but when I use something like `request.server.plugins['hapi-io'];` works as expected. So, there is anything that I missing or the docs are wrong?

I'm using hapi on version ^13.4.1

**Comment by sibartlett** [comment]
This has been fixed, in v0.1.0
