### ISSUE TITLE
Optional routing parameters won't work

### ISSUE THREAD

**Issue by Neonox31** [sibartlett/hapi-io#3]
Hi,

Before thanks a lot for hapi-io, it's exactly what i am looking for !
During plugin testing, i noticied that hapi optional routing parameters are not correctly reconized.

For example :

``` javascript
{
 method: 'GET',
 path: '/api/v1/plugins/{name?}',
 config : {
  plugins: {
   'hapi-io': 'get-plugins'
  },
  validate: {
   params: {
    name: Joi.string()
   }
  }
 }
}
```

Here we can ask the plugin list with "/api/v1/plugins" route or one plugin details with "/api/v1/plugins/dummy" with HTTP but it fails with SocketIO. When emit "get-plugins" event with no params, i get "plugin {name not found." with 404 code.

Hope this helps.

**Comment by sibartlett** [comment]
@Neonox31 thank you for reporting the issue - should now be fixed in the latest release!
