### ISSUE TITLE
How to use socket.io namespace?

### ISSUE THREAD

**Issue by khahantk** [sibartlett/hapi-io#33]

**Comment by mashaalmemon** [comment]
@sibartlett, following @khahantk's question, is there a way to limit a route to a specific namespace.

It appears that routing works as intended for the default "/" namespace. But if I try any other namespace, it doesn't hit the intended route at all. 

Suggested options: It may make sense to add a `namespace` property within the plugin settings for the route maybe? And the plugin should be listening on all namespaces specified in routes?
