### ISSUE TITLE
Project Being Maintained

### ISSUE THREAD

**Issue by mashaalmemon** [sibartlett/hapi-io#34]
Hi There @sibartlett ,

I am just inquiring, is this project being actively maintained? Please advise.

**Comment by hortonelectric** [comment]
+1, if it is not, then we need to start maintaining this as it seems to be a valid wrapper

**Comment by hortonelectric** [comment]
I was able to get this thing working after a little bit of doing. Pretty easy. If you have any questions about it... send me a message or something.

**Comment by sibartlett** [comment]
Yep, I'm still maintaining it. I haven't been using it recently, but will still look into reported issues, etc.

If you're experiencing issues with `hapi-io`, please advise 😄

**Comment by mashaalmemon** [comment]
@sibartlett Thanks so much for your quick response. Wanted to make sure before I jumped in with it and began to depend on it more heavily. I'll definitely let you know if I need some help. 👍 

@hortonelectric It looks like @sibartlett has got our backs! 😄 Thanks for the feedback though. I am about to explore and jump in and will be sure to ask if I have any questions.

One question I have that is very general. Are there any design patterns I should follow to keep myself organized while using the socket.io / hapi.js mashup with hapi.io? Ultimately socket.io has the namespace/room pattern. Any advice on how to use hapi.io and hapi routes "effectively" with socket.io? 

An explanation of my use case may help. I'm looking to have realtime interaction with:
- live monitoring and control of ongoing background server side jobs
- view current user interactions with the system
