### ISSUE TITLE
Upgrade to socket.io 2.0.x

### ISSUE THREAD

**Issue by jannostern** [sibartlett/hapi-io#56]
Hi Simon,

It seems socket.io has come out with 2.0.0 version recently.
Have you planned to upgrade and if so, then when?

Thanks,
Janno

**Comment by hhaidar** [comment]
+1

**Comment by sibartlett** [comment]
Updated to socket.io v2 in `0.2.0`

**Comment by jannostern** [comment]
Thanks Simon!
