### ISSUE TITLE
JWT Auth

### ISSUE THREAD

**Issue by sgentile** [sibartlett/hapi-io#6]
First, thank you for this create plugin!

We are using : https://www.npmjs.com/package/hapi-auth-jwt2 

Our Angular client handles sending the auth token on all our calls to the Hapi server endpoints.

ie. 

```
var _request = function (config) {

            var authService = $injector.get('authService');

            config.headers = config.headers || {};

            if (authService.authentication.isAuth) {
                config.headers.Authorization = 'Bearer ' + authService.authentication.token;
            }

            return config;
        };
```

When doing a socket.io emit from the client - I'm not sure how to send this token back to the server ?

**Comment by sibartlett** [comment]
Websockets/socket.io doesn't support setting headers, but you should be able to map a data parameter to the Authorization header as shown in the example below. Currently you'd have to configure the mapping for each route.

Server:

``` js
server.route({
  method: 'GET',
  path: '/messages',
  config: {
    'hapi-io': {
      event: 'get-events',
      mappings: {
        headers: ['Authorization']
      }
    }
  },
  handler: function(request, reply) {
    ...
  }
});
```

Client:

``` js
socket.emit('get-events',
            { Authorization: 'Bearer ' + authService.authentication.token, ... },
            function(data) {

});
```

**Comment by sgentile** [comment]
Thank you 

I tried this :

```
config: {
                auth: 'token',
                plugins: {
                    'hapi-io': {
                        event: 'get-tickets',
                        mappings: {
                            header: ['Authorization']
                        }
                    }
                },
                tags: ['api'],
                validate:{
                    params:{
                        tenantId: Joi.number().required()
                    }
                }
            },
```

client:

```
var socket = connect_socket(token);
        socket.emit('get-tickets', { tenantId: '1', Authorization: 'Bearer ' + token }, function(res){
            console.log('get-tickets', res);
        });
```

I put a debugger inside the hapi-auth-jwt2 here:

```
var scheme = {
    authenticate: function (request, reply) {
      var auth = request.headers.authorization;
      if (!auth) {
          return reply(Boom.unauthorized('Missing auth token'));
      }
```

It doesn't appear to be mapping to the request.headers.authorization object

**Comment by sgentile** [comment]
So I ended up adding a dataKeys item:  

plugins: {
                    'hapi-io': {
                        event: 'get-tickets',
                        mapping: {
                            headers: ['Authorization']
                        },
                        dataKeys: ['Authorization']
                    }
                },

As 'var newPath = path.replace(/(?:{(\w+)(\??)})/g, function(group, key, type) {' was not picking up the Authorization item

**Comment by sibartlett** [comment]
Sorry that I've been slow to reply. I'm away on a trip, and have not had good internet connectivity.

**Comment by sibartlett** [comment]
@sgentile sorry, the example I gave you is correct, but I had a typo; `mappings` should have been `mapping`.

**Comment by sgentile** [comment]
works well - thanks!

**Comment by sibartlett** [comment]
@sgentile the latest version of hapi-io now automatically replicates the "Authorization" attribute to headers - so you could try dropping the `mapping` object.

**Comment by sgentile** [comment]
wow - great- thank you Simon!
