### ISSUE TITLE
Namespaces break the plugin

### ISSUE THREAD

**Issue by vstanchev** [sibartlett/hapi-io#62]
In the latest 0.2.0 release in [`lib/routes.js`](https://github.com/sibartlett/hapi-io/blob/master/lib/routes.js#L22):

``` javascript
if (namespace == socketNamespace) {
  return;
}
```

I think `==` should be `!=`, because the route *should* be attached if namespaces match.

Tested with the example provided in the README.
I reverted to using 0.1.0 for now.

**Comment by sibartlett** [comment]
Should be fixed in `0.2.1`
